Increase and optimize HUD update speed, add advanced speed color options, track jumpbugs in HUD
KZGlobalTeam/gokz pull request #296
Opened 2022-03-29 01:26 UTC by zer0k-z

2022-05-01 10:33 UTC, zealain commented
I like the speed color changes, I think we can show the special jumpbug color even without the advanced option enabled and only put the airaccel thingy behind that option. Which I would then also rename a bit to make it more clear what it does.

Don't like the update rate changes though, all it does is make it faster and didn't really help when lagging either. The current update rate is deliberately not chosen to be higher to avoid a jittery feel to it.

2022-05-03 13:21 UTC, zer0k-z commented
The update rate change was meant to make full use of a player's good connection to the server with low ping. Its behavior should not change when the player has high ping at all.

For the jumpbug color, it is optional because a jumpbug is almost the exact same as a perf on kzt/skz. But I guess it wouldn't hurt knowing that either.

2022-05-03 16:39 UTC, zer0k-z commented
I forgot that there are two different changes to the update speed, depending on which one you use.

1. For the HUD text: This is just an improvement in all cases, more responsiveness is just better in all network scenarios. 21Hz update rate feels sluggish, especially compared to MovementHUD's 128Hz. Doubling it will be a very noticeable improvement while not reaching the point of diminishing returns and I doubt there is any downside at all to this.

2. For the center panel: The center panel update speed is painfully slow, 10x slower than MHUD. This discourages a lot of people from ever using this, which I think it's a shame. 

But the thing with center panel is that its maximum update speed depends on the ping between the player and the server. Right now it's the equivalent of player having 78ms ping to the server, but if they have a good connection to the server. I don't see why we shouldn't give them the best experience possible.

2022-05-04 10:11 UTC, zealain commented
As I already outlined before a faster update speed is **not** just a flat out improvement. It can make it more jittery and harder to read, making it just a matter of preference. As of right now, the update rate will not be increased. There is a widely available higher update rate alternative with mhud that people who prefer that experience can already use.

2022-05-04 10:27 UTC, zer0k-z commented
In that case, what about an option for higher update rate?

2022-05-04 10:46 UTC, zealain commented
An option is fine

2022-05-15 18:08 UTC, zealain requested changes

2022-05-15 18:08 UTC, zealain commented on addons/sourcemod/scripting/gokz-hud/racing_text.sp
> +	int updateSpeed = GOKZ_HUD_GetOption(client, HUDOption_UpdateRate) == UpdateRate_Fast ? 3 : 6;
Same as for the center panel

2022-05-15 18:08 UTC, zealain commented on addons/sourcemod/scripting/gokz-hud/speed_text.sp
> +	int updateSpeed = GOKZ_HUD_GetOption(client, HUDOption_UpdateRate) == UpdateRate_Fast ? 3 : 6;
Same as for the center panel

2022-05-15 18:08 UTC, zealain commented on addons/sourcemod/scripting/gokz-hud/timer_text.sp
> +	int updateSpeed = GOKZ_HUD_GetOption(client, HUDOption_UpdateRate) == UpdateRate_Fast ? 3 : 6;
Same as for center panel

2022-05-15 18:08 UTC, zealain commented on addons/sourcemod/scripting/gokz-hud/tp_menu.sp
> +	int updateSpeed = GOKZ_HUD_GetOption(client, HUDOption_UpdateRate) == UpdateRate_Fast ? 3 : 6;
Same as for center panel (man, there are a lot of update rates xD)

2022-05-15 18:08 UTC, zealain commented on addons/sourcemod/scripting/include/gokz/hud.inc
> +	DeadstrafeColor_Disabled
I believe this is missing a default for the update rate.

2022-05-30 08:50 UTC, zealain approved these changes

2022-05-30 08:50 UTC, merged