add simplified chinese translation
KZGlobalTeam/gokz pull request #431
Opened 2023-01-03 06:18 UTC by Cinyan10

#430

2023-01-03 16:15 UTC, Sikarii requested changes
Thanks a lot for doing this!
I went through the changes and theres a few things that need correcting.

2023-01-03 16:15 UTC, Sikarii commented on addons/sourcemod/translations/gokz-core.phrases.txt
> +		"en"		"{darkred}此区域禁止存点."
Wrong translation key, should probably be `"chi"` instead.

2023-01-03 16:15 UTC, Sikarii commented on addons/sourcemod/translations/gokz-core.phrases.txt
> +		"en"		"General"
Nitpick, but remove the added whitespace.

2023-01-03 16:15 UTC, Sikarii commented on addons/sourcemod/translations/gokz-core.phrases.txt
> +		"en"		"{blue}裸跳 {grey}保护模式已开启. 你不能再使用传送和会导致计时停止的命令."
Wrong translation key, should probably be `"chi"` instead.

2023-01-03 16:15 UTC, Sikarii commented on addons/sourcemod/translations/gokz-core.phrases.txt
> +		"en"		"Both Zones"
Revert the english translation back to the original, this PR shouldn't touch them.

2023-01-03 18:30 UTC, Sikarii approved these changes
Looks good!

2023-01-05 07:19 UTC, Cinyan10 commented
all translations completed

2023-01-07 10:30 UTC, merged